ln -s  prestashopconnect_deps/sale-wkfl/account_invoice_reorder_lines .
ln -s  prestashopconnect_deps/openerp-product-attributes/base_custom_attributes .
ln -s  prestashopconnect_deps/openerp-connector/connector/ .
ln -s  prestashopconnect_deps/connector/connector_base_product/ .
ln -s  prestashopconnect_deps/openerp-connector-ecommerce/connector_ecommerce/ .
ln -s  prestashopconnect_deps/openerp-product-attributes/customer_context_in_product_view .
ln -s  prestashopconnect_deps/sale-wkfl/mail_quotation .
ln -s  prestashopconnect_deps/sale-wkfl/partner_prepayment .
ln -s  prestashopconnect_deps/prestashoperpconnect/prestashoperpconnect .
ln -s  prestashopconnect_deps/prestashoperpconnect/prestashoperpconnect_catalog_manager/ .
ln -s  prestashopconnect_deps/prestashoperpconnect/prestashoperpconnect_pricelist/ .
ln -s  prestashopconnect_deps/sale-wkfl/pricelist_share_companies .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_brand .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_catalog_report .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_categ_attributes .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_custom_attributes .
ln -s  prestashopconnect_deps/sale-wkfl/product_customer_code_sale .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_electronic .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_extended .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_gift .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_gtin .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_icecat .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_images .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_index .
ln -s  prestashopconnect_deps/openerp-product-attributes/production_lot_custom_attributes .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_listprice_upgrade .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_lot_foundry .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_m2mcategories .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_multi_company .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_multi_price .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_pricelist_fixed_price .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_prices_on_variant .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_qt .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_quick_stock_rule .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_search_reference .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_sequence .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_series .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_size .
ln -s  prestashopconnect_deps/sale-wkfl/product_special_type .
ln -s  prestashopconnect_deps/sale-wkfl/product_special_type_invoice .
ln -s  prestashopconnect_deps/sale-wkfl/product_special_type_sale .
ln -s  prestashopconnect_deps/openerp-product-variant/product_variant_multi .
ln -s  prestashopconnect_deps/openerp-product-variant/product_variant_multi_advanced .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_weight .
ln -s  prestashopconnect_deps/openerp-product-attributes/product_with_supplier_unit_price .
ln -s  prestashopconnect_deps/sale-wkfl/purchase_order_reorder_lines .
ln -s  prestashopconnect_deps/e-commerce-7.0/sale_automatic_workflow .
ln -s  prestashopconnect_deps/sale-wkfl/sale_cancel_reason .
ln -s  prestashopconnect_deps/sale-wkfl/sale_condition_text .
ln -s  prestashopconnect_deps/sale-wkfl/sale_delivery_term .
ln -s  prestashopconnect_deps/sale-wkfl/sale_dropshipping .
ln -s  prestashopconnect_deps/sale-wkfl/sale_exception_nostock .
ln -s  prestashopconnect_deps/sale-wkfl/sale_exception_nostock_by_line .
ln -s  prestashopconnect_deps/sale-wkfl/sale_exceptions .
ln -s  prestashopconnect_deps/sale-wkfl/sale_fiscal_position_update .
ln -s  prestashopconnect_deps/sale-wkfl/sale_jit_on_services .
ln -s  prestashopconnect_deps/sale-wkfl/sale_line_description .
ln -s  prestashopconnect_deps/sale-wkfl/sale_multi_picking .
ln -s  prestashopconnect_deps/sale-wkfl/sale_order_force_number .
ln -s  prestashopconnect_deps/e-commerce-7.0/sale_payment_method/ .
ln -s  prestashopconnect_deps/sale-wkfl/sale_quotation_number .
ln -s  prestashopconnect_deps/sale-wkfl/sale_sourced_by_line .
ln -s  prestashopconnect_deps/sale-wkfl/sale_stock_global_delivery_lead_time .
ln -s  prestashopconnect_deps/sale-wkfl/sale_validity .
ln -s  prestashopconnect_deps/sale-wkfl/stock_picking_reorder_lines .
